(chore, ci): fix rare test flake
Cargo test locally failed for me with

```
failures:
---- channels::shared_channel::test::shared_drop_cascade_drop_executor_reverse stdout ----
thread 'unnamed-67' (3258883) panicked at glommio/src/channels/shared_channel.rs:140:63:
called Option::unwrap() on a None value
thread 'channels::shared_channel::test::shared_drop_cascade_drop_executor_reverse' (3258791) panicked at glommio/src/channels/shared_channel.rs:944:20:
called Result::unwrap() on an Err value: Thread panicked { .. }
failures:
channels::shared_channel::test::shared_drop_cascade_drop_executor_reverse
```

Couldn't reproduce but Codex explained the issue. The fix seems
sensible.

(cherry picked from commit 20d108cd4b5bf99a61fa4a753cb95ca4236babaf)